### get all admins
GET http://localhost:3000/api/admins

### POST new admin
# @name createAdmin
POST http://localhost:3000/api/admins
Content-Type: application/json 

{
  "dni": "85677898",
  "name": "Tirone",
  "surname": "Gonzales",
  "email": "ag3dg@gmail.com"
}
### ID
@id = {{createAdmin.response.body.data.id}}
### get admin by id
GET http://localhost:3000/api/admins/{{id}}

### Edit/modify admin (PUT - recurso completo/objeto con estado final)
PUT http://localhost:3000/api/admins/{{id}}
Content-Type: application/json

{
  "dni": "4576 ",
  "name": "Oliveeer",
  "surname": "Sykes",
  "email": "osbmth@gmail.com"
}


### Post a admin
# @name createAdminToDelete
POST http://localhost:3000/api/admins
Content-Type: application/json 

{
  "id": "2",
  "description": "Admin 2"
}

@idToDelete = {{createAdminToDelete.response.body.data.id}}
### delete admin
DELETE http://localhost:3000/api/admins/{{idToDelete}}

### Edit/modify admin (PATCH - Modificaciones parciales/modificaciones incrementales)
PATCH http://localhost:3000/api/admins/{{idToDelete}}
Content-Type: application/json

{
  "email": "updatedemail@gmail.com"

}