### get all courses
GET http://localhost:3000/api/courses
### create new course

# @name createCourse
POST http://localhost:3000/api/courses
Content-Type: application/json 

{
    "title": "Curso de React",
    "price": 100,
    "level": 1
  }

### ID
@id = {{createCourse.response.body.data.id}}

### get course by id
GET http://localhost:3000/api/courses/{{id}}

### Edit/modify course (PUT - recurso completo/objeto con estado final)
PUT http://localhost:3000/api/courses/{{id}}
Content-Type: application/json

{
  "tittle": "***",
  "price": "40"
}

### POST a course
# @name createCourseToDelete
POST http://localhost:3000/api/courses
Content-Type: application/json 

{
  "tittle": "***",
  "price": "30"
}

###
@idToDelete = {{createCourseToDelete.response.body.data.id}}
### delete course
DELETE http://localhost:3000/api/courses/{{idToDelete}}


### Edit/modify course (PATCH - Modificaciones parciales/modificaciones incrementales)
PATCH http://localhost:3000/api/courses/{{idToDelete}}
Content-Type: application/json

{
  "price": "8"
}

