### get all users
GET http://localhost:3000/api/members

### POST new user
# @name createUser
POST http://localhost:3000/api/members
Content-Type: application/json 

{
  "dni": "85674898",
  "name": "Tirone",
  "surname": "Gonzales",
  "email": "ag3dg@gmail.com"
}
### ID
@id = {{createUser.response.body.data.id}}
### get user by id
GET http://localhost:3000/api/members/{{id}}

### Edit/modify user (PUT - recurso completo/objeto con estado final)
PUT http://localhost:3000/api/members/{{id}}
Content-Type: application/json

{
  "dni": "4576 ",
  "name": "Oliveeer",
  "surname": "Sykes",
  "email": "osbmth@gmail.com"
}


### Post a user
# @name createUserToDelete
POST http://localhost:3000/api/members
Content-Type: application/json 

{
  "id": "2",
  "description": "User 2"
}

@idToDelete = {{createUserToDelete.response.body.data.id}}
### delete user
DELETE http://localhost:3000/api/members/{{idToDelete}}

### Edit/modify user (PATCH - Modificaciones parciales/modificaciones incrementales)
PATCH http://localhost:3000/api/members/{{idToDelete}}
Content-Type: application/json

{
  "email": "updatedemail@gmail.com"

}